-- CreateTable
CREATE TABLE "SoloRecord" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "peakDb" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SoloRecord_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "SoloRecord" ADD CONSTRAINT "SoloRecord_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
